COUNTRIES = {
    'Albania': 'AL',
    'Argentina': 'AR',
    'Australia': 'AU',
    'Austria': 'AT',
    'Bangladesh': 'BD',
    'Belgium': 'BE',
    'Bolivia': 'BO',
    'Bosnia and Herzegovina': 'BA',
    'Botswana': 'BW',
    'Brazil': 'BR',
    'Bulgaria': 'BG',
    'Chile': 'CL',
    'Colombia': 'CO',
    'Costa Rica': 'CR',
    'Croatia': 'HR',
    'Ecuador': 'EC',
    'Georgia': 'GE',
    'Germany': 'DE',
    'Ghana': 'GH',
    'Hungary': 'HU',
    'India': 'IN',
    'Indonesia': 'ID',
    'Israel': 'IL',
    'Italy': 'IT',
    'Japan': 'JP',
    'Kenya': 'KE',
    'South Korea': 'KR',
    'Lebanon': 'LB',
    'Malawi': 'MW',
    'Malaysia': 'MY',
    'Mexico': 'MX',
    'Nigeria': 'NG',
    'Pakistan': 'PK',
    'Panama': 'PA',
    'Paraguay': 'PY',
    'Peru': 'PE',
    'Philippines': 'PH',
    'Poland': 'PL',
    'Romania': 'RO',
    'Russian Federation': 'RU',
    'Rwanda': 'RW',
    'Serbia': 'RS',
    'Slovenia': 'SI',
    'Solomon Islands': 'SB',
    'South Africa': 'ZA',
    'Sri Lanka': 'LK',
    'Sweden': 'SE',
    'Thailand': 'TH',
    'Trinidad & Tobago': 'TT',
    'Turkey': 'TR',
    'United Kingdom': 'GB',
    'United States': 'US',
    'Uruguay': 'UY',
    'Venezuela': 'VE',
}